/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.6.1/samples
 */
// Áp dụng plugin Java cho root project
plugins {
    java
    `java-library`
}

// HOẶC nếu bạn muốn cấu hình cho tất cả subprojects
subprojects {
    apply(plugin = "java-library")

    repositories {
        mavenCentral()
    }

    java {
        toolchain {
            languageVersion.set(JavaLanguageVersion.of(25)) // Dùng 25 LTS thay vì 25
        }
    }

    // Cấu hình encoding
    tasks.withType<JavaCompile>().configureEach {
        options.encoding = "UTF-8"
    }

    tasks.withType<JavaExec>().configureEach {
        jvmArgs = listOf(
            "-Dfile.encoding=UTF-8",
            "-Dsun.stdout.encoding=UTF-8",
            "-Dsun.stderr.encoding=UTF-8"
        )
    }

    tasks.withType<Test>().configureEach {
        useJUnitPlatform()
        jvmArgs = listOf(
            "-Dfile.encoding=UTF-8",
            "-Dsun.stdout.encoding=UTF-8",
            "-Dsun.stderr.encoding=UTF-8"
        )
    }
}